Export your personal [[https://hypothes.is][Hypothes.is]] data: annotations and profile information.

* Setting up
1. Clone *recursively*: =git clone --recursive https://github.com/karlicoss/hypexport=. This is important so Hypothesis API are cloned as well.
2. =pip3 install --user -r requirements.txt=
3. Follow [[https://hypothes.is/account/developer][these]] instructions to set up the token

* Exporting

#+begin_src python :results drawer :exports results 
import export; return export.make_parser().epilog
#+end_src

#+RESULTS:
:results:

Usage:

*Recommended*: create =secrets.py= keeping your api parameters, e.g.:


: username = "USERNAME"
: token = "TOKEN"


After that, use:

: ./export.py --secrets /path/to/secrets.py

That way you type less and have control over where you keep your plaintext secrets.

*Alternatively*, you can pass parameters directly, e.g.

: ./export.py --username <username> --token <token>

However, this is verbose and prone to leaking your keys/tokens/passwords in shell history.

    
You can also import ~export.py~ this as a module and call ~get_json~ function directly to get raw JSON.


I *highly* recommend checking exported files at least once just to make sure they contain everything you expect from your export. If not, please feel free to ask or raise an issue!
    
:end:

# TODO FIXME api limitations 10000 annotations?
